### ISSUE TITLE
min/max temperature query 

### ISSUE THREAD

**Issue by DavideDC9** [j-c-cook/ghedt#101]
Is it possible to automatically select a configuration based on the minimum/maximum temperature after steady-state e.g 25 years?

**Comment by j-c-cook** [comment]
I want to make sure I fully understand your question.

The following are your inputs:
- Minimum heat pump entering fluid temperature
- Maximum heat pump entering fluid temperature
- Design life 

With those inputs, you would like to automatically select a configuration?

**Comment by DavideDC9** [comment]
I get this error message :
length = dt.utilities.length_of_side(number_of_boreholes, B)
AttributeError: module 'ghedt.utilities' has no attribute 'length_of_side'

**Comment by j-c-cook** [comment]
This same thing happened the other day here: https://github.com/j-c-cook/ghedt/issues/97

You'll need to use the examples from the [version 0.1 release](https://github.com/j-c-cook/ghedt/releases/tag/v0.1) if you've installed from [PyPi](https://pypi.org/project/ghedt/).

**Comment by DavideDC9** [comment]
Solved.
Is there a way to see the temperature profile for the designated period?

**Comment by j-c-cook** [comment]
You'll want the `hours` of simulation utilized by the hybrid time step and the `heat_pump_exit_fluid_temp`. 
```
hours = ghe.hybrid_load.hour[2:]  # Hour of Simulation
heat_pump_exit_fluid_temp = ghe.HPEFT  # Heat Pump Exiting Fluid temperature
```
I would plot these as a scatter plot. 
```
ax.scatter(hours, heat_pump_exit_fluid_temp)
```

**Comment by j-c-cook** [comment]
@DavideDC9 I think this should get you going. If you think there's something we could get going in [Discussions](https://github.com/j-c-cook/ghedt/discussions) that could help you further analyze the ground heat exchangers you are designing or something that could help a user in the future, please feel free to start a new discussion or comment on an existing.
