### ISSUE TITLE
x_new is above the interpolation range

### ISSUE THREAD

**Issue by DavideDC9** [j-c-cook/ghedt#104]
I have tried to run the examples with a different load profile. Same type and length as hourly_extraction_ground_loads variable. 
The warning is : 
![image](https://user-images.githubusercontent.com/84395463/153461326-f3e1dd8c-31e8-4c91-9664-4b7cbbcda749.png)

**Comment by j-c-cook** [comment]
I cannot confirm the validity of this issue. I have not been provided adequate information. I will be closing this issue for the time being. 

I will be happy to address this issue if I am provided with the necessary information. The information I need is how the error message was created. Such as: the version of `ghedt`, the example script used and the inputs. Feel free to re-open this issue if you are able to provide the necessary information. 

Please refer to the issue template I have now created for [bugs](https://github.com/j-c-cook/ghedt/issues/new?assignees=&labels=bug&template=bug_report.md&title=), this [ideal bug issue post](https://github.com/j-c-cook/ghedt/issues/84#issue-1111668154) or follow up with me at my email at jack-c-cook@protonmail.com

**Comment by DavideDC9** [comment]
Sorry for the late reply. I have updated ghedt to the latest version and seem to work fine now. I just get this runtime warning: Find bi-rectangle...
====================
Note: This routine requires a nested bisection search.
Do some initial checks before searching.
C:\Users\davide\------------------------\ground_heat_exchangers.py:168: RuntimeWarning: invalid value encountered in log
  g_values = g(np.log((_time * 3600.) / ts))
Size between min and max of lower bound in domain.

**Comment by j-c-cook** [comment]
[Issue 82](https://github.com/j-c-cook/ghedt/issues/82) is open and will address the runtime warning. The warning has no impact on the final results. 

The Python Package Index [PyPi](https://pypi.org/project/ghedt/) is where Python projects are published to. When you run `pip install ghedt`, you are accessing download links from PyPi. Yesterday I published `ghedt-v0.2` to PyPi. It sounds like maybe that is what changed for you.
