### ISSUE TITLE
Could not install ghedt

### ISSUE THREAD

**Issue by XiaoliLiu94** [j-c-cook/ghedt#107]
Hi. I was not able to install ghedt using pip install ghedt. 
Error: Could not find a version that satisfy the requirement ghedt
Error: No matching distribution found for ghedt

There is no package named ghedt in pypi.org. 
Could you please let me know how I can install this package? Thank you!

**Comment by XiaoliLiu94** [comment]
I figured it out.

**Comment by j-c-cook** [comment]
To install the most recent release, `v0.2`:
`pip install https://github.com/j-c-cook/ghedt/archive/refs/tags/v0.2.zip`
To install the current `main` branch:
`pip install git+https://github.com/j-c-cook/ghedt@main`

I'll get `v0.2` pushed up to PyPi soon.
