### ISSUE TITLE
Interpolation Out-of-range Error

### ISSUE THREAD

**Issue by mitchute** [j-c-cook/ghedt#84]
When running the attached loads, I'm seeing an interpolation out-of-range error in `perform_current_month_simulation` function, here:

https://github.com/j-c-cook/ghedt/blob/92ec5deda47ac801be7a553d70685ee9d3a8b6ef/ghedt/peak_load_analysis_tool/ground_loads.py#L439

Calling from the `Bisection1D` search routine, and setting a breakpoint at line 440 of that function, I'm seeing

`max(dT_fluid_pk) = 12.208312117009044`
`dT_fluid_nm_max = 27.59003818526601`
`min(dT_fluid_pk) = 0.0`

Thus causing the out-of-bounds interpolation error. It's unclear currently what the underlying issue is.

![image](https://user-images.githubusercontent.com/2985979/150652978-98f3cc62-1529-48a1-8f06-7eea7c866d74.png)

[4509.csv](https://github.com/j-c-cook/ghedt/files/7919127/4509.csv)

GHEDT SHA: 92ec5deda47ac801be7a553d70685ee9d3a8b6ef

**Comment by mitchute** [comment]
The max/min values for `q_peak` and `q_nominal` seem to be out of sorts, so that's one potential starting point.

![Screen Shot 2022-01-22 at 12 42 07 PM](https://user-images.githubusercontent.com/2985979/150653233-9025226b-27c5-4a96-b2b0-cb1391f435aa.png)

**Comment by j-c-cook** [comment]
The bug is in the peak load analysis of the heating load for the 5th month. 

The following is cooling load information for month 5:
```
current_month_peak_cl == 405.07
current_month_avg_cl = 60.39
```
The peak load analysis concludes a `peak_duration == 1.63`.

The following is heating load information for month 5:
```
current_month_peak_hl == 33.4
current_month_avg_hl == 0.308
```
The peak load analysis is throwing an error in finding the bug. The nominal load. `q_nominal` in position 7 has a value of 39.6 while the peak load `q_peak` is 33.096. 

My intuition says that this load should be near 0. This bug is interesting. I may have seen something like it before. I'll need to dig a little bit. In the meantime if you need results @mitchute , I recommend using `ghe.size(method='hourly'))` to entirely skip the peak load analysis. The only downside is that it will take significantly longer. I'll try to resolve this today.

**Comment by j-c-cook** [comment]
The design interface does not currently allow the user to define the method. Therefore, the default of `hybrid` is utilized when searching for a field. This did not occur to me until I recommended that the `hourly` method be used to determine a field while a bug was being fixed. I have always used `hourly` to validate `hybrid` and will just setup a `ghe` and simulate it. 

This enhancement is a matter of modifying the API in a few places.

**Comment by mitchute** [comment]
I think I've found what might be part of the problem.

To pick the peak heating and cooling loads, you're searching within that month, but then you grab the day prior as well to get your two-day peak loads. That'll fine if you stay only within that month's data. However, in this case, the peak heating load happens on the first hour of the month, so you are reaching back into the previous month to get the two-day loads, and that day has a higher peak load than the "peak" you've already picked.

![Screen Shot 2022-01-22 at 6 55 34 PM](https://user-images.githubusercontent.com/2985979/150661562-30c66994-0d4a-477d-bdf8-abaef927133b.png)

I haven't tried this, but I would try passing the max of the two-day loads in here, instead of the actual peak that falls in that calendar month.

https://github.com/j-c-cook/ghedt/blob/92ec5deda47ac801be7a553d70685ee9d3a8b6ef/ghedt/peak_load_analysis_tool/ground_loads.py#L412

**Comment by mitchute** [comment]
Also, I think we may have talked about this day-ahead load picking before - but if not, I just want to make sure you're not doing that for the *actual* first day of the simulation.  We really do not have load history before the beginning of the simulation, so in that case, it doesn't make sense to wrap the end of the year back onto the front of the simulation. 

You may have already figured that out, but it was in my mind, so I thought I'd get it out here.

**Comment by j-c-cook** [comment]
That makes sense. Do you want to open a PR and make the change you suggest? If so, point to https://github.com/j-c-cook/ghedt/pull/88.

**Comment by mitchute** [comment]
Sure, give me a minute. If it works, I'll push a branch and make a PR.
